dist: trusty
matrix:
  include:
  - language: node_js
    node_js: 10
    before_install:
      - cd frontend/
    install:
      - npm install
    script:
      - echo "== RUNNING FRONTEND TESTS =="
      - npm run test
  
  - language: python
    python: 3.4
    before_install:
      - cd backend/
    install:
      - python -m pip install -r requirements.txt
    script:
      - echo "== RUNNING BACKEND TESTS =="
      - pytest
