# Using in develop docker run -p 80:80 --network=host franky-static

# **
# * Build fronted
# **
FROM node:10-alpine as react

# RUN useradd -r runner
# USER runner

WORKDIR /home/runner/franky/frontend
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build

# **
# * Configure nginx for static
# **
FROM nginx
COPY --from=react /home/runner/franky/frontend/build /var/www/franky

# volume
VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/var/log/nginx"]
# # expose ports
EXPOSE 80 443
# add nginx conf
ADD config/nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf
WORKDIR /etc/nginx
CMD ["nginx", "-g", "daemon off;"]

