# Using in develop docker run -p 80:80 --network=host franky-static

# **
# * Build fronted
# **
FROM node:10-alpine as react

# RUN useradd -r runner
# USER runner

WORKDIR /home/runner/franky/frontend
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build

# **
# * Configure nginx for static
# **
FROM nginx:stable-alpine
COPY --from=react /home/runner/franky/frontend/build /var/www/franky

# # expose ports
EXPOSE 80 443
# add nginx conf
ADD config/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /etc/nginx
CMD ["nginx", "-g", "daemon off;"]

