# docker swarm init(once)
# cp config/nginx/nginx.prod.conf config/nginx/nginx.conf
# docker-compose build
# docker stack deploy --compose-file docker-stack.yml franky

version: '3.3'
 
services:
  frankyapp:
    image: franky_frankyapp:latest
    networks:
      main:
    expose:
      - "5000"
    deploy:
      mode: replicated
      replicas: 2 
  nginx:
    networks:
      main:
    image: franky_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frankyapp
networks:
  main:
